name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-standalone:
    runs-on: ubuntu-latest
    outputs:
      ZIP_NAME: ${{ steps.setzip.outputs.ZIP_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Linux
        id: setzip
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          PUBLISH_DIR="$GITHUB_WORKSPACE/QuicFileSharing.GUI/bin/Release/net9.0/linux-x64/publish"

          dotnet publish ./QuicFileSharing.GUI/QuicFileSharing.GUI.csproj \
            -c Release \
            -r linux-x64 \
            --self-contained true \
            /p:UseAppHost=true \
            /p:Version=$VERSION

          cp ./QuicFileSharing.Core/runtimes/linux-x64/native/libmsquic.so "$PUBLISH_DIR/"

          ZIP_NAME="QuicShare-v${VERSION}-linux-x64.zip"

          cd "$PUBLISH_DIR"
          zip -r "$GITHUB_WORKSPACE/$ZIP_NAME" .

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ${{ steps.setzip.outputs.ZIP_NAME }}

  build-flatpak:
    runs-on: ubuntu-latest
    outputs:
      FLATPAK_NAME: ${{ steps.bundle.outputs.FLATPAK_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flatpak Tools
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Install SDK & Platform
        run: |
          flatpak install -y flathub org.freedesktop.Sdk//25.08
          flatpak install -y flathub org.freedesktop.Platform//25.08

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean build-dir io.github.zemendaniel.QuicShare.yaml

      - name: Export Repo & Bundle Flatpak
        id: bundle
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          # Create a repo directory
          flatpak-builder --force-clean --repo=repo build-dir io.github.zemendaniel.QuicShare.yaml

          FLATPAK_NAME="QuicShare-v${VERSION}.flatpak"

          flatpak build-bundle repo "$FLATPAK_NAME" io.github.zemendaniel.QuicShare master

          echo "FLATPAK_NAME=$FLATPAK_NAME" >> $GITHUB_OUTPUT

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak
          path: ${{ steps.bundle.outputs.FLATPAK_NAME }}

  release:
    needs: [build-standalone, build-flatpak]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: .

      - name: Download Flatpak Artifact
        uses: actions/download-artifact@v4
        with:
          name: flatpak
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ needs.build-standalone.outputs.ZIP_NAME }}
            ${{ needs.build-flatpak.outputs.FLATPAK_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
