name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-standalone:
    runs-on: ubuntu-latest
    outputs:
      ZIP_NAME: ${{ steps.setzip.outputs.ZIP_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Linux
        id: setzip
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          PUBLISH_DIR="$GITHUB_WORKSPACE/QuicFileSharing.GUI/bin/Release/net9.0/linux-x64/publish"

          dotnet publish ./QuicFileSharing.GUI/QuicFileSharing.GUI.csproj \
            -c Release \
            -r linux-x64 \
            --self-contained true \
            /p:UseAppHost=true \
            /p:Version=$VERSION

          cp ./QuicFileSharing.Core/runtimes/linux-x64/native/libmsquic.so "$PUBLISH_DIR/"

          ZIP_NAME="QuicShare-v${VERSION}-linux-x64.zip"

          cd "$PUBLISH_DIR"
          zip -r "$GITHUB_WORKSPACE/$ZIP_NAME" .

          # Output ZIP name for next job
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ${{ steps.setzip.outputs.ZIP_NAME }}

  release:
    needs: build-standalone
    runs-on: ubuntu-latest
    steps:
      - name: Download Standalone Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build-standalone.outputs.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
